In [1]:
import sys
sys.path.append('../..')
import numpy as np
from pysrc.pamm import PAMM

In [2]:
runner = PAMM(dimension=2,
              ngrid=2000,
              gridfile='ref.idxs',
              fspread=0.15,
              qs=0.95,
              outputfile='fs0.15-qs0.95',
              verbose=True)

In [3]:
descriptors = np.loadtxt('data-rings.dat')

In [4]:
result = runner.run(descriptors)

 Precalculate distance matrix between grid points
Global eff. dim. 1.9999979632895026
Estimating kernel density bandwidths
  0 / 2000
  100 / 2000
  200 / 2000
  300 / 2000
  400 / 2000
  500 / 2000
  600 / 2000
  700 / 2000
  800 / 2000
  900 / 2000
  1000 / 2000
  1100 / 2000
  1200 / 2000
  1300 / 2000
  1400 / 2000
  1500 / 2000
  1600 / 2000
  1700 / 2000
  1800 / 2000
  1900 / 2000
Computing kernel density on reference points
  0 / 2000
  100 / 2000
  200 / 2000
  300 / 2000
  400 / 2000
  500 / 2000
  600 / 2000
  700 / 2000
  800 / 2000
  900 / 2000
  1000 / 2000
  1100 / 2000
  1200 / 2000
  1300 / 2000
  1400 / 2000
  1500 / 2000
  1600 / 2000
  1700 / 2000
  1800 / 2000
  1900 / 2000
Starting Quick-Shift
  0 / 2000
idxn=1808
lambda_=4.2863011052020905
probs=array([ -6.33548796, -13.65157464, -13.08502455, ...,  -7.79633138,
       -10.68361048,  -8.57263947])
distmm[0]=array([         inf, 947.10482593, 605.03950381, ..., 779.19589861,
        24.639435  ,  85.75725702])
180

In [5]:
runner.idxroot

array([ 995,   41,  228, ..., 1061,  402,  168])

In [6]:
runner.probs

array([ -6.33548796, -13.65157464, -13.08502455, ...,  -7.79633138,
       -10.68361048,  -8.57263947])

In [7]:
from pysrc.pamm import logsumexp

In [29]:
logsumexp(idx - 1, runner.probs, 41)

-2.959593817408874

In [9]:
from scipy.special import logsumexp as LSE

In [13]:
LSE(runner.probs[runner.idxroot == 42])

-2.807870937885263

In [16]:
result = -np.inf
for prob in runner.probs[runner.idxroot == 41]:
    if result > prob:
        result += np.log(1 + np.exp(prob - result))
    else:
        result = prob + np.log(1 + np.exp(result - prob))

In [17]:
result

-3.4741866442682987

In [6]:
idx = np.array([eval(s) for s in ' 996          42         229        1194        1927        1395         305        1255         751         890         778         551         403         169         573         906          43        1255        1255        1383        1194        1380         551        1062        1691         890         229         832         519        1231         573         260        1576        1857         305         403         996        1202         473        1062         260          42          43         815        1395        1927        1202        1576        1065        1383         751        1255          53        1231         169          43         305        1395        1194        1062         551        1194         751        1194         519          53        1383         573         778         551         890        1194         551         169        1576        1395        1691          43        1927         403         832         890         519         573         519        1062         996         260        1194         229         551         996        1691         519        1194         573         832        1857         229          43        1331         305        1231        1383         169        1380         573        1927         519        1202         229        1395         519        1194        1576         403        1194        1576        1576         996         996        1062        1255         260        1383          43         890        1062          53         403        1395         551        1927        1194        1383        1255        1062        1194        1395        1255        1927         260         473        1062        1062        1202          42         778         890         473        1576         815        1255        1395        1194         890        1576         906         403         832         778         305        1395        1654         473         906         403        1231         169          53         551        1395         169        1927         573        1857        1255          42          43         996        1231         229         305        1395         229         260         519         551        1202         305        1383         551         573         890        1194         260         260         519        1691         473         403        1691          43         751        1395         890         832        1255        1576         229         778         996         890         519         551         778         169        1194         229         573         305         403        1691         169          42         751         778        1194         229         815        1194        1576         573        1927         305          43         519         551         573         778         778        1380         906         519        1062        1202        1576         229         169        1194        1395        1383         519         890         815         573         832         519         551         260        1927        1576         519         890        1194         305         229        1255         832        1383         519          43         403        1927        1395         169        1654         573         815        1062        1194         906         305         551         305        1194         996         996         906         890         996         832        1857         260          42         573        1691         519          43         890         260         778         519         996         305         996        1576        1383         519          43        1062        1062        1062        1062         996         832        1383         996        1202         403         260         573         305          42        1395        1202         473          43        1194          43        1194         832          53         890         347        1194          53         473          43        1380        1255          43         551         473        1062         906         347        1194         996        1194         751        1194         996        1255         815        1395         573         229        1927        1194        1395         890         751        1383         169        1576        1231        1255         996         906        1194        1380        1231          53        1231        1255        1065        1383        1576        1062         551         996          42         832        1062         519         403         996        1395        1395        1331         473        1202         169         260        1576        1255        1383        1576        1065        1202         169         403         403          53        1395        1194        1927        1691        1654         305        1395         229         996         751         890        1576        1231         169        1062        1383         573         403        1383        1062        1062         890        1383         260         573         815         551         906        1927         305        1194        1255         890         573         169         519        1194        1576        1255         260         260         751          53          42        1255          42         229        1194         551          43          42         551         832        1331         551         906         890        1194        1331        1331         778        1927         996        1062         519         260         519         473         305        1395         832        1194         890         229          43         229        1691          42         305        1576        1194         229         403         573         996        1654        1691        1255        1380        1194         403         778         890        1927         169         890        1576         473         778        1927        1194         403         551         519         890         519         573        1395         778         751         519        1202         551         519         403        1202        1576          53         890         519        1395        1383         260        1231         169        1395        1255        1927        1395        1395         815        1194        1255         169         751         890         169         229        1383        1202          43        1194         403        1231         473         551          53        1062        1231         778         832        1383        1576         815        1395        1395        1062         519         169         906         305        1395        1395         260         403        1857         996         573        1857         229         403        1927         551          43        1395        1062         169         519         906         473         751        1927         573        1576         229         996        1194         832         169         229         573        1062         573         473         551         260         551         890         473         815         260         260          43         169         403         229         890        1062         519         778        1062         403        1691         551        1691         519          42        1576        1654         260        1062        1062        1691        1395          42          42        1383          43         551          53        1255        1383          43          42         260         890         906         260          43         519        1383         260         832        1691         519        1576         305          43        1395         551         519         573        1927          43         519        1062        1202         229         519        1395         169         260          53        1383         229          53         305         305        1576        1194         890         260          43        1194        1857         519         778         305        1331         305         519        1383         551         519        1395        1194         473          53        1062        1380         573         260         778          43         260         403         260        1194         573         573         519         573        1927         305         890         403         169         778        1383        1194         832        1202        1395        1062         996         573         519         519         778         519         573        1194        1194          43         890         573         832         305         305         751         473         906        1395         996        1395        1857        1062         260        1255        1691        1691         403        1065        1255        1395         751         169         573         573         778         229        1194          53        1383         229        1383         305        1194        1383        1202        1194         305         778         229         751         751         890        1857          43         551        1202          42         778         832         890          42         229         169         519         573        1395         832        1231         169        1231        1380        1194         815        1927         305         996        1576          43         996         519        1255        1194        1255         551        1062        1194         996         573         996         403        1194         573         778         403         815          43        1576         778         815         551         519        1194         519         403        1927         996        1231         169          43        1255         229         832         473         519         890        1062         996         229         996         890        1202        1576        1194          43          43        1395        1194         260         473         751         573         996        1062         778        1065          43         403         403          43        1194         573        1395         832         229        1691         751        1255         832          42         305         751        1395         229        1383         573         832        1255        1576         229        1576        1691          42        1576        1194         305        1576         519         996        1194         890        1062        1927          42        1395          43         906          42        1255          43         573        1194        1062         473        1062         890         906         573          43         996         305        1255        1383        1576         169        1927         229         169         519          53          43        1202        1255        1383         832          53         305         573         347        1202         890         890        1202        1202        1383         996        1065        1231         519         403         260          53         996         996         778         305        1927         229        1202         305        1857        1395         260        1380        1194        1194         778         551        1576         305        1395        1927         906        1255        1576        1194         996         890         551         169        1927         890          53         996         996         890        1255        1255          42        1202         473        1194         551         305         169        1231         229        1255         996         519         815        1202         906         890         573         169         996         519        1062          53         305         890        1383         996         778         996         403          53        1255        1062         996        1194        1062         305         473        1927          42         551        1062        1194        1576         778         519         229        1395         573        1062         473         573        1395         551          43        1395         229        1576         890         832        1927         890         305          43         260         519         305          43         996         347        1202         815         169          42        1062         519        1062         778        1654          53        1927         996         996         890        1576        1062        1065         169        1065        1202        1202         229        1691        1194        1654          43        1857        1395        1194         778        1380         519        1927         815         169         403         403         305        1331        1395         551         832         260        1576         519         815        1383         890         996        1062          43        1576         778        1383        1194         260          42        1065          43         832        1691        1194         403         169         305         519        1062          43        1576         573        1383        1380         996        1062          43        1383         519        1395         519         832         473         996         403         890         260        1383         551        1691        1194        1383         751         229        1331        1576        1395         347         169         551        1062         519         573         473        1194        1383         403         832        1202        1395         519         832         573         778        1255        1331         169        1231          53        1062        1202        1383         890        1380         260         551        1383         260         996          53          53         996         832         473         519          43        1062        1062         832          53          43        1691        1231        1576         403         519        1062         906         519        1194         751         403        1255         229         573        1194        1194        1202         996        1202         551         519        1194        1395         906          53         778         473        1331        1231         551         832         906        1194        1395          43        1395        1255         573        1231        1395        1194        1194        1194        1255         169        1231         890        1065         169          43        1576         519         519          42        1395        1576         751        1576          42         551        1395        1065        1202         551         573        1380         996          53         229        1255         305         403        1255         906         473         906        1331          43        1383         551        1383         996         519        1395         906        1576          53         778        1380         890         403        1194        1654        1231        1194          43         403         890         305         890         260         519        1927        1062         305        1062         403         169        1927         778        1927        1691         890        1576        1383         751        1576        1395         573        1576        1395         551        1062        1231         473        1383         403         519        1062         751        1194         473        1194         890         778        1927         815        1202          43        1255        1194        1927        1691         906         996        1331         169         519         551        1255        1202        1927        1202         519         519        1331         169         573         260        1395        1202        1576         260         751          53         751         260        1576         519        1395         751         751         260        1576        1395          42        1255         832         305        1255         403        1654         778         473         751         169        1395          53         815         551        1255         519        1927         229        1380         260        1927        1383         403         519         751         573         751        1383         751        1654         403         551         473        1395        1255         832        1576          43         229         551        1383         260         169         832        1395          53        1927        1194         551         573        1395         519         169        1691          42        1691         890        1194         996        1383        1194        1576        1383        1576         403         519          42         815        1857         573        1380        1576         169         573        1194         305         260         519         403        1062         551         305         778        1194         551         473        1576        1383        1255        1927         751         751        1380        1062         906         169         229        1062         519        1395          42        1202         473        1231         778        1927         260         573         815        1576        1576        1194         305        1927         551         996         890         573        1202         403         996         169         890          43        1395         260         229         305        1255         832         551          42         403        1576        1576          42        1383         403         260        1395        1383          53          43         551        1395        1062         815        1576        1927         169         890          42         519          42         551         890        1062         890         260         573        1857         169        1062        1062         551         169         403        1194        1383         229        1062         890         305        1395         519        1395         169        1395         996         573         906        1194         260         260         403        1927         169         169        1380         473        1654         519          53         519         519         169        1194        1395         305         403        1383        1202        1380         906          43        1062         403        1194         551         305         260         778        1062        1395        1576         403        1194          53         519        1194         832        1383        1194         890        1202        1857        1194         519        1255        1194         229        1202         229         778        1231        1062        1691        1231         778        1383        1691         890         573         260        1383         473         573        1691        1691         890        1395         778         832         473         778        1691         815         260        1691         229         169        1231        1231         890        1395         890        1062          42        1383          42        1857        1395        1062          42        1576         832          53        1927         473        1576        1062         906         890        1383         751         890         519         751        1194         169         260         778        1654         551         260         403        1380         169         473        1194        1194         260         778         229         260         519         551         832         996         996         815         906         229        1231          43        1194         573        1062          42         890         551         573        1691         305        1062         229        1576         305          53        1691         305         519        1927        1231        1194         890        1255         551          42        1383         996         778        1231         229          43         169         551         519        1231        1380         996        1857        1383         890         890         890        1194        1194        1255        1395         473         305         519        1691        1331         778         551         519         832         260        1062         890         260         751        1395         996         229         519        1255        1927        1395         403         996        1576        1395        1691        1395         890         573         890        1202        1194        1194         815          43         403         229         778         551        1255        1331         551         890        1062         473         403        1395        1062        1576          43         996        1062         778         260        1395        1194          42          43        1691        1331        1255        1927         573        1857        1194        1202        1255         890        1395        1062         403        1927          43         551        1395         260         519         573         519         260         890         473         260         996         890         832        1857         996          53         260        1202        1395        1255         906         890         403         519         403         519         996         229         573         832        1395         260        1202         229         229        1927         751         551        1927        1194         260         551         305        1395         519        1927        1202        1062         751        1576         473        1194         815        1576        1576         260         260        1395         519         519        1395        1194        1857         473        1395         519         573        1202        1383         519        1576         260        1927         815          42        1691         832         751         229        1231         229        1062         573         305         573        1231        1691          43         403        1255        1383         305         519        1062         403          42         305        1395         778          43         519         573        1383         573         260         996         169         473         473        1194        1062         305        1255          42         169         551        1383          43          43         815         519         169        1202        1255         169         751          43         305         778        1395         890        1927        1927         519         832         573         778         573          43        1383         573        1395         519        1194        1062         260         519         169        1576         996        1576         519         551         815        1194        1194         778         169        1380         778         519         519         996        1194        1383         403        1691         551         890         890        1194         403         229         519          43         519         305         751         260         815         890        1576         229         305        1194         305        1194         403        1202        1857        1395        1194        1194         778         751         573        1255         551         996         229         778         996        1395        1062         403         169'.split()])

In [8]:
idx[63] = np.inf

In [11]:
runner.idxroot[63]

674

In [7]:
np.allclose(idx - 1, runner.idxroot)

True

In [24]:
idx - 1

array([ 995,   41,  228, ..., 1061,  402,  168])

In [25]:
runner.idxroot

array([ 995,   41,  228, ..., 1061,  746,  168])

In [15]:
idx[63]

1194

In [16]:
runner.idxroot[63]

674

In [6]:
np.argwhere((idx - 1) != runner.idxroot)

array([[0]])

In [8]:
runner.idxroot

array([ 402,   41,  228, ..., 1061,  402,  168])

In [22]:
assert np.allclose(idx - 1, runner.idxroot)

AssertionError: 

In [5]:
runner.get_output('output-rings.dat')